
path: C:\Users\ranuj\Documents\6. Semester\Machine Learning II\ML2 Final Project\licenseplate-recognition-training-kumarran26\data_new # dataset root dir
train: images\train  # train images (relative to 'path')
val: images\train  # val images (relative to 'path')

# Classes
names:
  0: licenseplate